### ISSUE TITLE
unable to show graphics

### ISSUE THREAD

**Issue by jbrodriguez** [tarkah/tickrs#145]
looks like yahoo finance is not working, im getting an animation of progressive dots

![Screenshot 2023-07-17 at 14 32 42](https://github.com/tarkah/tickrs/assets/1305422/3ae8787c-57ce-4386-9905-db591def9845)

any thoughts ?

**Comment by brihuang99** [comment]
Running into the same issue here. I can still see the Volume and Options charts on my end though

**Comment by sid-the-sloth** [comment]
Me too, getting progress dots... no data coming in. Maybe yahoo is blocking these.

Suggest using a free API such as: `twelve-data1.p.rapidapi.com` which allows every user to provide their own API key (on linux systems RAPIDAPIKEY is obtained from user ~./bashrc).

**Comment by JacquardCauseway** [comment]
Thought it was just me, also getting this issue.

**Comment by Esfo** [comment]
same

**Comment by SigmaticThar** [comment]
Same problem for me. kmymoney stopped updating from yahoo and the new URL that works is https://query1.finance.yahoo.com/v8/finance/chart/%1
If I could manage to compile this without having to go through dependency hell I would get in there and try to fix this.

**Comment by SigmaticThar** [comment]
BTW the only thing that would need to change in the code is likely V7 to V8

**Comment by JacquardCauseway** [comment]
Tried to change it and compile locally as well, likewise ran into dependency hell. :(

**Comment by tarkah** [comment]
Hey all, I just did a quick check and it appears to be the `https://query1.finance.yahoo.com/v10/finance/quoteSummary/SPY` endpoint which is failing. I use this to get company profile info & current price info. I already use `v8` for `chart` endpoint, I've confirmed that works.

I'm getting `{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}` on the `v10/finance/quoteSummary` endpoint. Does anyone know an alternative endpoint to get this information?

**Comment by tarkah** [comment]
This has been fixed in https://github.com/tarkah/tickrs/pull/146

The `quotes` endpoints now require a cookie & `crumb` value to work. I'll cut a release soon.

**Comment by SigmaticThar** [comment]
> This has been fixed in #146
> 
> The `quotes` endpoints now require a cookie & `crumb` value to work. I'll cut a release soon.

Thanks for getting this fixed! I can also confirm it's now working in Arch after update pacman -Syu

**Comment by jbrodriguez** [comment]
it's still not working for me, 0.14.9 :(

i remember a couple of weeks ago there was an issue with the yahoo enpoints and the country where the request was made from, for example, those in the EU had a different signature (or something like that) that those in the US, i'll try to find the issue

**Comment by JacquardCauseway** [comment]
@jbrodriguez Do you have a long update interval by any chance? I noticed that when I start `tickrs` the issue still appears until the first update tick.

For example, I have the interval set to 120s. So the issue still appears until 120s has elapsed after running the app.

**Comment by jbrodriguez** [comment]
thank you @JacquardCauseway, i had the interval set to 60, changed to 5, but same issue,  this is my command 
```
tickrs --show-x-labels --summary --update-interval 5  --symbols VOO,BTC-USD,CL=F,^GSPC
```

**Comment by SigmaticThar** [comment]
> it's still not working for me, 0.14.9 :(
> 
> i remember a couple of weeks ago there was an issue with the yahoo enpoints and the country where the request was made from, for example, those in the EU had a different signature (or something like that) that those in the US, i'll try to find the issue

If you have a VPN or if you can sign up to a free VPN to test your theory that would help.

**Comment by SigmaticThar** [comment]
Actually if you can tell me what country you would like to test I can try it on my VPN if you're okay with that

**Comment by jbrodriguez** [comment]
hi @SigmaticThar , thanks for the offer ! does it work for you from mexico ?

**Comment by SigmaticThar** [comment]
> hi @SigmaticThar , thanks for the offer ! does it work for you from mexico ?

Yes I just tested Mexico and it works.

**Comment by SigmaticThar** [comment]
At this point I think you should try from a free VPN on your end and use a US server and that will tell you for sure if it's something on your computer or a country connection. I also use the program mop and while I was connected to London it wasn't working so your country theory is possible.

**Comment by tarkah** [comment]
Are you using a pihole or adblocker? I noticed the fc.yahoo.com domain was blocked on mine and I had to whitelist it. We have to hit this endpoint to get a cookie.

**Comment by jbrodriguez** [comment]
thanks guys, i'll try both the vpn and the adblocker check, yes i'm running adblock on my router, i'll test and report back

**Comment by jbrodriguez** [comment]
success !! i whitelisted fc.yahoo.com and got it working ! thank you !
