### ISSUE TITLE
Not working. Project abandoned?

### ISSUE THREAD

**Issue by yonas** [tarkah/tickrs#166]
`tickrs` is not showing any stock information.

Has this project been abandoned?

**Comment by miguno** [comment]
+1 same here

**Comment by shawnyeager** [comment]
All was well for me until last night; stopped updating. Still not updating today.

**Comment by cwarden** [comment]
Setting a user agent fixes the 429, Edge: Too Many Requests, errors, e.g. fecdaf4d902dc9ca4b806e32c7787925827a9762.

HT: https://github.com/ranaroussi/yfinance/pull/2277

**Comment by shawnyeager** [comment]
This worked like a champ for me, @cwarden. Thank you.

@tarkah could we get this merged, please?

**Comment by tarkah** [comment]
Thanks @cwarden, do you mind opening a PR with that patch? I'll merge and get a new release out

**Comment by cwarden** [comment]
I've opened #170

**Comment by tarkah** [comment]
This fix is released: https://github.com/tarkah/tickrs/releases/tag/v0.14.11

**Comment by ristomatti** [comment]
I just tested this. The issue is gone, thank you!

**Comment by RaffaeleBianc0** [comment]
Hello, just updated tickrs to the latest version, but still have the same behaviour as before: 
- only volume data is shown (no performance)
- the 3 dots following the ticker name keep spinning forever 
- the top-right menu only shows the "S" choice, all the others are missing

All the above happens on any ticker I choose.

![Image](https://github.com/user-attachments/assets/1e8d38ca-1f5c-484f-85b4-f6f748cf2861)

If there is anything I can do to help, like any log file to share, I will be glad to help.

**Comment by Lucasvo1** [comment]
Are you using a DNS-based ad-blocker or VPN? Maybe check if you can whitelist fc.yahoo.com.

**Comment by ckl** [comment]
> Are you using a DNS-based ad-blocker or VPN? Maybe check if you can whitelist fc.yahoo.com.

Thank you for mentioning this. It fixed the issue for me as well.

**Comment by Blumenkohl-OS** [comment]
Since 2 days tickrs is not working on several devices. Does anyone know what happend?

**Comment by shawnyeager** [comment]
I'm also unable to pull data since yesterday.

**Comment by shawnyeager** [comment]
> Curiously I've had it running for several days and it keeps pulling data. However if I start a new instance, it won't pull any data.

Same here. I was delayed in noticing until I tried to launch on a different machine.

**Comment by cwarden** [comment]
The Yahoo API is returning 429 Too Many Requests errors again.

There's a long thread here about trying to get past the rate limiting:
https://github.com/ranaroussi/yfinance/issues/2422#issuecomment-2840759533

It sounds like a whac-a-mole situation.

**Comment by JacquardCauseway** [comment]
Is there an equivalent library in Rust that can be used here? Although yea, does seem like a whac-a-mole situation...

**Comment by lvanoverberghe** [comment]
All these issues eventually all get fixed when Yahoo changes something.
If you don't want to wait, there are paid APIs available: https://polygon.io/pricing.
It doesn't seem like a big effort to integrate something like this.

**Comment by JacquardCauseway** [comment]
Right you were lol, seems like it's back to working today...

**Comment by ristomatti** [comment]
Forgot this thread, tickrs has been working again for quite some time for me also. Same does not apply to achannarasappa's [ticker](https://github.com/achannarasappa/ticker). Every time I want to open the app, I need to have a VPN connection from e.g. Switzerland or Washington open. After the app shows tickers, VPN connection can be closed. 😄
